# https://hub.docker.com/_/mongo
version: '3.1'

services:
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: webrtc_serv
      MONGO_INITDB_ROOT_PASSWORD: webrtc_serv
    ports:
      # https://docs.mongodb.com/manual/reference/default-mongodb-port/
      - '47017:27017' # TODO need to make it bind to localhost, not 0.0.0.0